// Newly authored, synthetic portfolio demonstrations. No client task data or live AI.
const blue='#80b4ff',ink='#dce8f7',muted='#99aec8',amber='#efbe76';
const text=(x,y,value,size=15,color=ink)=>`<text x="${x}" y="${y}" fill="${color}" font-size="${size}" font-family="Arial,sans-serif">${value}</text>`;
const line=(x1,y1,x2,y2,color=blue,width=2)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}"/>`;
const box=(x,y,w,h,label,active=false)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="5" fill="${active?'#294a72':'#17283d'}" stroke="${active?blue:'#48607e'}"/>${text(x+12,y+h/2+5,label,14)}`;
const svg=(title,body)=>`<svg viewBox="0 0 600 250" role="img" aria-label="${title}">${body}</svg>`;
const select=(label,values)=>`<label>${label}<select>${values.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
const range=(label,min,max,val,step=1)=>`<label>${label}<input type="range" min="${min}" max="${max}" value="${val}" step="${step}"></label>`;
function shell(el,controls,caption){el.innerHTML=`<p class="demo-label">ILLUSTRATIVE PORTFOLIO DEMO</p><div class="demo-visual" tabindex="0" aria-label="Interactive diagram. On narrow screens, scroll horizontally to inspect the full diagram."></div><p class="demo-mobile-hint">Swipe the diagram sideways to inspect.</p><div class="demo-controls">${controls}</div><p class="demo-status" aria-live="polite"></p><p class="demo-caption">${caption}</p>`;el.dataset.ready='true';return {visual:el.querySelector('.demo-visual'),status:el.querySelector('.demo-status')}}
function wire(el,fn){el.querySelectorAll('select,input').forEach(c=>c.addEventListener(c.tagName==='SELECT'?'change':'input',fn));fn()}
const demos={};
demos.floor=el=>{
 const {visual,status}=shell(el,range('Driven sprocket teeth',16,48,32,2),'New chain-drive concept, not original scrubber CAD. Ideal ratio only; losses, traction and other gearing are excluded.');
 wire(el,()=>{const n=+el.querySelector('input').value,r=n*1.5,ratio=n/16;visual.innerHTML=svg('Two sprockets linked by a chain. The driven sprocket grows with its tooth count.',`${line(160,106,430,130-r)}${line(160,154,430,130+r)}<circle cx="160" cy="130" r="24" fill="#263c57" stroke="${blue}" stroke-width="7" stroke-dasharray="5 4"/><circle cx="430" cy="130" r="${r}" fill="#263c57" stroke="${blue}" stroke-width="7" stroke-dasharray="5 4"/>${text(142,136,'16',19)}${text(414,136,n,19)}${text(99,215,'INPUT · 60 rpm',15)}${text(358,215,`OUTPUT · ${(60/ratio).toFixed(1)} rpm`,15)}${text(236,43,`${ratio.toFixed(2)} : 1 ratio`,21,blue)}`);status.textContent=`${n} driven teeth / 16 input teeth = ${ratio.toFixed(2)}:1. At 60 rpm input, ideal output speed is ${(60/ratio).toFixed(1)} rpm and torque multiplication is ${ratio.toFixed(2)}×.`})
};
demos.lumiere=el=>{
 const {visual,status}=shell(el,range('Output angular speed (rad/s)',0,12,4),'New clutch-power illustration. Constant illustrative friction torque: 12 N·m. It does not reproduce the private evaluation task or verify holding capacity.');
 wire(el,()=>{const w=+el.querySelector('input').value,slip=Math.abs(8-w),power=12*slip,a=w/12*Math.PI*2;visual.innerHTML=svg('Input and output clutch discs with a bar showing sliding power.',`<circle cx="130" cy="117" r="59" fill="#243c59" stroke="${blue}" stroke-width="5"/><circle cx="365" cy="117" r="59" fill="#243c59" stroke="${amber}" stroke-width="5"/>${line(130,117,170,78)}${line(365,117,365+46*Math.sin(a),117-46*Math.cos(a),amber,4)}${line(190,117,305,117,muted)}${text(65,210,'INPUT · 8 rad/s')}${text(289,210,`OUTPUT · ${w} rad/s`)}${text(482,60,`${power} W`,24,amber)}<rect x="493" y="78" width="38" height="120" fill="#17283d"/><rect x="493" y="${198-power/96*120}" width="38" height="${power/96*120}" fill="${amber}"/>`);status.textContent=`Relative speed = ${slip} rad/s. Sliding power = 12 × ${slip} = ${power} W. ${slip===0?'Zero slip does not by itself prove that the clutch can hold the applied load.':'The illustration shows dissipated sliding power, not total system efficiency.'}`})
};
demos.planck=el=>{
 const {visual,status}=shell(el,range('Complex-number angle (degrees)',15,165,60,15),'A new mathematical illustration of complex conjugation, one type of sign check relevant to the reviewed physics work. Not a historical task or quantum simulation.');
 wire(el,()=>{const deg=+el.querySelector('input').value,a=deg*Math.PI/180,re=Math.cos(a),im=Math.sin(a),x=180+80*re,y=123-80*im;visual.innerHTML=svg('A complex number and its conjugate mirrored across the real axis.',`${line(55,123,305,123,muted)}${line(180,18,180,228,muted)}<circle cx="180" cy="123" r="80" fill="none" stroke="#456180"/>${line(180,123,x,y,blue,3)}${line(180,123,x,246-y,amber,3)}<circle cx="${x}" cy="${y}" r="6" fill="${blue}"/><circle cx="${x}" cy="${246-y}" r="6" fill="${amber}"/>${text(x+12,y,'z',20,blue)}${text(x+12,246-y,'z*',20,amber)}${text(286,146,'Re',12)}${text(193,25,'Im',12)}${text(342,78,`z = ${re.toFixed(3)} + ${im.toFixed(3)}i`,18,blue)}${text(342,122,`z* = ${re.toFixed(3)} − ${im.toFixed(3)}i`,18,amber)}${text(342,181,'z × z* = 1',23)}${text(342,209,'Unit magnitude; opposite imaginary sign.',12,muted)}`);status.textContent=`At ${deg}°, conjugation preserves the real part (${re.toFixed(3)}) and reverses the imaginary sign (${im.toFixed(3)} to ${(-im).toFixed(3)}).`})
};
demos.neutron=el=>{
 const {visual,status}=shell(el,range('Candidate hole centre, x (mm)',25,35,30,.5),'New 60 × 40 mm plate example. Drawing target: x = 30 ± 0.2 mm, hole Ø8 mm. An illustrative inspection, not supplied project CAD.');
 wire(el,()=>{const x=+el.querySelector('input').value,ok=Math.abs(x-30)<=.2;visual.innerHTML=svg('A dimensioned plate drawing compared with a candidate isometric part.',`${text(35,35,'DRAWING TARGET',13,muted)}<rect x="35" y="60" width="210" height="140" fill="none" stroke="${ink}" stroke-width="2"/><circle cx="140" cy="130" r="14" fill="none" stroke="${blue}" stroke-width="2"/>${line(35,217,140,217)}${line(35,206,35,228)}${line(140,146,140,228)}${text(58,242,'30 ± 0.2 mm',13,blue)}${text(160,113,'Ø8',14)}${text(322,35,'CANDIDATE GEOMETRY',13,muted)}<path d="M320 95 L480 55 L555 135 L395 175 Z" fill="#537ca9" stroke="${ink}"/><path d="M395 175 L555 135 L555 157 L395 197 L320 117 L320 95 Z" fill="#263e5b" stroke="#779bc3"/><ellipse cx="${350+x*2.9}" cy="115" rx="16" ry="10" fill="#102033" stroke="${ok?blue:amber}" stroke-width="3"/>${text(345,225,`${x.toFixed(1)} mm · ${ok?'within example tolerance':'outside example tolerance'}`,15,ok?blue:amber)}`);status.textContent=`Candidate deviation: ${(x-30).toFixed(1)} mm. ${ok?'Inside':'Outside'} the ±0.2 mm example tolerance. The drawing, geometry and grading condition must agree.`})
};
demos.mercor=el=>{
 const {visual,status}=shell(el,select('Inspect a test case',[['normal','[2, 4]'],['empty','[]']]),'New toy Python example and synthetic test cases. This demonstrates review reasoning, not an actual reviewed repository or model score.');
 wire(el,()=>{const empty=el.querySelector('select').value==='empty';visual.innerHTML=svg('A code expression connected to its input, test result and review finding.',`${text(32,37,'CODE UNDER REVIEW',12,muted)}${box(32,52,535,54,'average = sum(values) / len(values)')}${box(32,151,125,55,empty?'input: []':'input: [2,4]',true)}${line(157,179,201,179)}${box(201,151,167,55,empty?'division by zero':'result: 3',empty)}${line(368,179,410,179)}${box(410,151,157,55,empty?'needs a guard':'case passes',true)}`);status.textContent=empty?'The empty-input case exposes an unhandled zero denominator. Revision feedback should identify this case and the required behaviour.':'This test passes, but one passing case does not establish complete correctness. Inspect the empty-input case too.'})
};
demos.novel=el=>{
 const {visual,status}=shell(el,select('Choose a remembered fact',[['relevant','Prefers short study explanations'],['irrelevant','Enjoys football']]),'Fictional user and response snippets. This is a relevance demonstration, not a private task, trainer record or actual user profile.');
 wire(el,()=>{const relevant=el.querySelector('select').value==='relevant';visual.innerHTML=svg('A user request, a remembered fact and a response connected through a relevance check.',`${box(25,26,550,44,'REQUEST: Explain gear ratio for my revision.')}${box(25,102,245,57,relevant?'Short study explanations':'Enjoys football',true)}${line(270,130,316,130,relevant?blue:amber,3)}${box(316,102,259,57,relevant?'Useful style preference':'No clear help for this answer')}${box(25,196,550,38,relevant?'RESPONSE: Ratio = driven teeth / driving teeth.':'Better choice: leave the unrelated memory out.',true)}`);status.textContent=relevant?'A relevant preference improves the explanation without adding unnecessary personal details.':'A fact can be true and still be unhelpful here. Relevance and useful impact matter more than mentioning a memory.'})
};
demos.ivy=el=>{
 const {visual,status}=shell(el,select('Input records',[['unique','A, B, C'],['duplicates','A, A, B']]),'New synthetic comparison. A and B are illustrative responses, not named models or recorded evaluation outcomes.');
 wire(el,()=>{const dup=el.querySelector('select').value==='duplicates',expected=dup?2:3;visual.innerHTML=svg('Two candidate counting methods compared against the same unique-item requirement.',`${text(30,30,'REQUIREMENT: COUNT UNIQUE ITEM IDS',13,muted)}${box(30,48,540,43,dup?'INPUT: A, A, B':'INPUT: A, B, C',true)}${box(30,117,250,68,'A · count all rows → 3',!dup)}${box(320,117,250,68,`B · count distinct → ${expected}`,true)}${text(44,220,dup?'A: fails this case':'A: passes this case',16,dup?amber:blue)}${text(334,220,'B: passes this case',16,blue)}`);status.textContent=dup?'Expected 2 unique IDs. Response A returns 3; response B returns 2. Rate each response using its own evidence.':'Both return 3 on this input. A second test with repeated IDs distinguishes their behaviour.'})
};
demos.insight=el=>{
 const {visual,status}=shell(el,select('Inspect the submitted output',[['valid','Correct value and unit'],['unit','Missing unit'],['value','Wrong value']]),'New deterministic checking example. Expected output: {"value": 12, "unit": "N"}. No live model, container or private grading logic.');
 wire(el,()=>{const v=el.querySelector('select').value,ok=v==='valid';visual.innerHTML=svg('A task passes through a solution, output file and independent checks.',`${box(24,72,125,60,'Task spec',true)}${line(149,102,166,102)}${box(166,72,126,60,'Solution')}${line(292,102,309,102)}${box(309,72,125,60,'Output file',true)}${line(434,102,451,102)}${box(451,72,125,60,'Checks',ok)}${text(45,184,v==='unit'?'Output: { value: 12 }':v==='value'?'Output: { value: 10, unit: N }':'Output: { value: 12, unit: N }',19)}${text(45,224,ok?'Value and unit checks pass.':v==='unit'?'Unit check fails.':'Value check fails.',16,ok?blue:amber)}`);status.textContent=ok?'This example passes two explicit checks. Real tasks need checks matched to their complete requirements.':v==='unit'?'A numerically correct value is incomplete when the required unit is missing.':'The file is present and formatted, but its value is wrong. Checking file existence alone would miss this failure.'})
};
demos.artemis=el=>{
 const {visual,status}=shell(el,select('Trace the answer to its source',[['schedule','Schedule · page 2'],['memo','Planning memo · page 1']]),'Fictional documents and dates created for this demonstration. No internal document contents are used.');
 wire(el,()=>{const right=el.querySelector('select').value==='schedule';visual.innerHTML=svg('A question connected to a source page and a supported or unsupported answer.',`${text(30,29,'QUESTION: WHEN IS FINAL INSPECTION?',14)}<rect x="30" y="52" width="245" height="169" rx="5" fill="#23364e" stroke="#587799"/>${text(47,79,right?'Schedule / page 2':'Planning memo / page 1',15,blue)}${line(48,98,251,98,muted)}<rect x="43" y="116" width="220" height="40" fill="#355b80"/>${text(51,141,right?'Final inspection: Friday':'Draft review: Wednesday',14)}${line(275,136,330,136,right?blue:amber,3)}${box(330,91,237,91,right?'ANSWER: Friday':'Wrong activity',true)}${text(335,212,right?'Relevant source + exact evidence':'Evidence does not answer it',13,right?blue:amber)}`);status.textContent=right?'Friday is supported by the schedule entry for final inspection. The source location stays attached to the answer.':'Wednesday refers to a draft review, not final inspection. A matching date alone is not enough evidence.'})
};
demos.seal=el=>{
 const {visual,status}=shell(el,select('Inspect an archival source',[['map','Map'],['ledger','Shipment ledger'],['log','Departure log']]),'A fictional mini-archive. The dock names and entries are invented only to demonstrate cross-source research.');
 wire(el,()=>{const v=el.querySelector('select').value;let content=v==='map'?`${line(70,70,260,70,blue,8)}${line(70,150,260,150,blue,8)}${text(75,55,'Dock A')}${text(75,135,'Dock B')}${text(316,96,'MAP: the wharf has two docks.',18)}`:v==='ledger'?`${box(45,54,510,50,'Ledger: cargo K7 → vessel Elm',true)}${box(45,128,510,50,'Cargo alone does not identify a dock.')}`:`${box(45,54,510,50,'Departure log: vessel Elm → Dock B',true)}${box(45,128,510,50,'Join with ledger: cargo K7 → Dock B',true)}`;visual.innerHTML=svg('Three fictional archival sources combine to locate a cargo shipment.',`${text(32,25,'WHERE DID CARGO K7 DEPART?',14,muted)}${content}${text(45,223,'Map → shipment ledger → departure log',16,blue)}`);status.textContent=v==='map'?'The map establishes locations but does not connect cargo K7 to a vessel.':v==='ledger'?'The ledger links K7 to Elm. The departure log is still needed to identify the dock.':'Combining the ledger and departure log supports Dock B, which can then be located on the map.'})
};
demos.mark=el=>{
 const rows=[['A','Aligned','On','No'],['B','Offset','On','Yes'],['C','Aligned','Off','No'],['D','Offset','Off','Yes']];
 const {visual,status}=shell(el,select('Inspect a possible factor',[['fixture','Fixture alignment'],['cooling','Cooling state']]),'Four synthetic observations, not measured manufacturing results. A pattern supports a hypothesis; a controlled test is still needed for a causal conclusion.');
 wire(el,()=>{const f=el.querySelector('select').value;visual.innerHTML=`<table class="demo-table"><caption>Synthetic observations</caption><thead><tr><th>Run</th><th class="${f==='fixture'?'selected':''}">Fixture</th><th class="${f==='cooling'?'selected':''}">Cooling</th><th>Slip</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td class="${(f==='fixture'&&i===1)||(f==='cooling'&&i===2)?'selected':''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`+svg('Selected evidence points toward a testable hypothesis.',`${box(35,82,210,58,f==='fixture'?'Offset fixture':'Cooling on / off',true)}${line(245,111,330,111)}${box(330,82,235,58,f==='fixture'?'Slip in both shown cases':'Slip under both states')}${text(55,203,f==='fixture'?'Next: control other variables and test alignment.':'This table does not separate the cooling effect.',16,blue)}`);status.textContent=f==='fixture'?'Fixture offset tracks slip in this small synthetic table. It is a candidate cause to test, not a proven causal result.':'Slip appears with cooling both on and off. The evidence here is weaker for cooling as the explanation.'})
};
demos.dynamo=el=>{
 let step=0;const events=['Start with an empty state.','Apply event E1: part A = new.','Save checkpoint after E1.','Apply event E2: part A = inspected.','Connection lost; resume from checkpoint.','Replay E2: overwrite the same key, do not duplicate it.'];
 const {visual,status}=shell(el,'<button type="button" data-next>Next event</button><button type="button" data-reset>Reset</button>','New deterministic checkpoint/replay illustration. It explains a concept, not the full historic benchmark or its acceptance results.');
 function draw(){const current=step===0?'empty':step<3?'A = new':'A = inspected';visual.innerHTML=svg('An event stream feeds a checkpoint and a keyed output state.',`${[0,1,2,3,4,5].map((n)=>`${n<5?line(57+n*94,65,151+n*94,65,n<step?blue:muted):''}<circle cx="${57+n*94}" cy="65" r="16" fill="${n<=step?'#426fa3':'#1b2d43'}" stroke="${blue}"/>${text(52+n*94,70,n,13)}`).join('')}${box(35,125,235,72,step>=2?'CHECKPOINT: after E1':'CHECKPOINT: none',step>=2)}${box(330,125,235,72,`STATE: ${current}`,true)}${text(36,230,step===5?'Replay stays idempotent: one part record.':'Follow the sequence to inspect replay behaviour.',15,blue)}`);status.textContent=events[step];el.querySelector('[data-next]').disabled=step===5}el.querySelector('[data-next]').onclick=()=>{step++;draw()};el.querySelector('[data-reset]').onclick=()=>{step=0;draw()};draw()
};
demos.openclaw=el=>{
 const {visual,status}=shell(el,select('Request content',[['safe','Summarise a maintenance document'],['private','Include a private contact number']]),'New local agent-workflow illustration. No live LLM, tool connection, personal records or deployment. It is separate from the agent built during Outlier work.');
 wire(el,()=>{const privateRequest=el.querySelector('select').value==='private';visual.innerHTML=svg('An agent request flows through a document tool, evidence review and privacy boundary.',`${box(25,37,150,55,'User request',true)}${line(175,64,218,64)}${box(218,37,162,55,'Document tool',true)}${line(380,64,425,64)}${box(425,37,150,55,'Evidence')}${line(501,92,501,135)}${box(319,135,256,55,'Privacy boundary',true)}${line(319,162,271,162,privateRequest?amber:blue,3)}${box(25,135,246,55,privateRequest?'Private detail withheld':'Maintenance summary',!privateRequest)}${text(30,226,privateRequest?'The workflow blocks an unnecessary private detail.':'The answer keeps its connection to document evidence.',16,privateRequest?amber:blue)}`);status.textContent=privateRequest?'The illustration stops the private detail at the boundary. It does not pretend to retrieve or expose a real phone number.':'The request uses a document source, retains evidence and produces the requested maintenance summary.'})
};
demos.touchstone=el=>{
 let i=0,position=0,faults=0,done=false;const cargo=[0,1,1,0,1,0];
 const {visual,status}=shell(el,'<button type="button" data-left>← Blue bay</button><button type="button" data-right>Amber bay →</button><button type="button" data-place>Place cargo</button><button type="button" data-restart>Restart</button>','New playable sorting mini-game for this portfolio, not one of the historical Touchstone builds. Match six crates to their coloured bays. Three faults end the round.');
 el.tabIndex=0;el.setAttribute('aria-label','Sorting game. Left or right chooses a bay, space places cargo, R restarts.');
 function draw(){const col=cargo[Math.min(i,5)]===0?blue:amber;visual.innerHTML=svg('A coloured cargo crate above two sorting bays.',`${text(28,29,`PLACED ${i}/6 · FAULTS ${faults}/3`,15,muted)}${text(387,29,done?(i===6?'ROUND COMPLETE':'ROUND ENDED'):'SORT THE CRATE',14,done?amber:blue)}<path d="M90 78 H510" stroke="#4a6483" stroke-width="8"/>${!done?`<rect x="${position===0?133:398}" y="53" width="58" height="58" rx="4" fill="${col}" stroke="#edf5ff" stroke-width="2"/>${text(position===0?145:409,89,cargo[i]===0?'BLUE':'AMBER',cargo[i]===0?12:10,'#122034')}`:''}<rect x="65" y="145" width="190" height="78" fill="#203f61" stroke="${blue}" stroke-width="${position===0?5:2}"/><rect x="340" y="145" width="190" height="78" fill="#59462f" stroke="${amber}" stroke-width="${position===1?5:2}"/>${text(113,191,'BLUE BAY',18,blue)}${text(375,191,'AMBER BAY',18,amber)}`);el.querySelector('[data-place]').disabled=done;status.textContent=done?(i===6?'All six crates sorted. Use Restart to play again.':'Three faults reached. Use Restart to try again.'):`${i} of 6 sorted; ${faults} of 3 faults. Crate ${i+1} is ${cargo[i]===0?'blue':'amber'}. Selected bay: ${position===0?'blue':'amber'}.`;}
 function place(){if(done)return;if(position===cargo[i])i++;else faults++;done=i===6||faults>=3;draw()}
 function reset(){i=0;faults=0;position=0;done=false;draw()}
 el.querySelector('[data-left]').onclick=()=>{position=0;draw()};el.querySelector('[data-right]').onclick=()=>{position=1;draw()};el.querySelector('[data-place]').onclick=place;el.querySelector('[data-restart]').onclick=reset;
 el.addEventListener('keydown',e=>{if(e.target!==el)return;if(e.key==='ArrowLeft')position=0;else if(e.key==='ArrowRight')position=1;else if(e.key===' '){place();e.preventDefault();return}else if(e.key.toLowerCase()==='r'){reset();return}else return;e.preventDefault();draw()});draw()
};

demos.auren=el=>{
 let step=0;
 const {visual,status}=shell(el,select('Sample voice request',[['time','What time is it?'],['codex','Open Codex'],['delete','Delete a file']])+'<button type="button" data-next>Next step</button><button type="button" data-reset>Reset</button>','Illustrative command walkthrough based on the AUREN prototype. Sample time: 10:30 AM. No microphone, desktop control or AI provider is connected here.');
 const labels=['VOICE TRANSCRIPT','COMMAND ROUTING','ACTION CHECK','REPLY'];
 function draw(){
  const command=el.querySelector('select').value,blocked=command==='delete',color=blocked?amber:blue;
  const request=command==='time'?'What time is it?':command==='codex'?'Open Codex':'Delete a file';
  const route=command==='time'?'Read local time':command==='codex'?'Open or focus app':'Removal request';
  const states=[`Sample transcript: “${request}”`, `AUREN recognises the request and selects: ${route.toLowerCase()}.`,blocked?'The removal check asks for the exact target and confirmation. Nothing is changed.':'The selected local command can proceed. This portfolio only illustrates the action.',blocked?'Sample reply: Please confirm the exact target. Nothing has been changed.':command==='time'?'Sample reply: It is 10:30 AM.':'Sample reply after a successful controller result: Opening Codex. A failure would need a different reply.'];
  const bars=[12,25,41,61,79,53,31,47,69,42,21];
  visual.innerHTML=svg('AUREN voice request moving through transcript, command routing, action check and reply.',`<circle cx="117" cy="125" r="83" fill="#192e49" stroke="${color}" stroke-width="2"/><circle cx="117" cy="125" r="68" fill="none" stroke="#3c5879"/>${bars.map((h,i)=>line(57+i*12,125-h/2,57+i*12,125+h/2,i<=step*3?color:muted,5)).join('')}${text(86,229,'AUREN',17,color)}${labels.map((label,i)=>`${i<3?line(250,48+i*55,250,103+i*55,i<step?color:muted):''}<circle cx="250" cy="${43+i*55}" r="14" fill="${i<=step?'#365a82':'#17283d'}" stroke="${i===step?color:muted}"/>${text(246,48+i*55,i+1,12)}${text(279,41+i*55,label,12,i===step?color:muted)}${text(279,59+i*55,[request,route,blocked?'Confirmation required':'Local command selected',blocked?'No action taken':command==='time'?'Sample: 10:30 AM':'Result-aware spoken reply'][i],15,i<=step?ink:muted)}`).join('')}`);
  status.textContent=`Step ${step+1} of 4. ${states[step]}`;
  el.querySelector('[data-next]').disabled=step===3;
 }
 el.querySelector('select').onchange=()=>{step=0;draw()};
 el.querySelector('[data-next]').onclick=()=>{if(step<3)step++;draw()};
 el.querySelector('[data-reset]').onclick=()=>{step=0;draw()};draw();
};

// These lightweight SVG examples initialise once so anchor navigation does not
// jump when a previously unseen diagram adds height above the destination.
document.querySelectorAll('[data-demo]').forEach(el=>{try{demos[el.dataset.demo](el)}catch(error){el.innerHTML='<p>Interactive example unavailable. The project description remains above.</p>';console.error('Portfolio demonstration failed:',error)}});
