import * as T from 'three';
import {OrbitControls} from './assets/OrbitControls.js';
import {RoomEnvironment} from './assets/RoomEnvironment.js';
const silver=new T.MeshStandardMaterial({color:0xaac0d9,metalness:.65,roughness:.3});
const blue=new T.MeshStandardMaterial({color:0x397cce,metalness:.6,roughness:.32});
const dark=new T.MeshStandardMaterial({color:0x26374c,metalness:.45,roughness:.4});
const rubber=new T.MeshStandardMaterial({color:0x101923,roughness:.8});
function box(g,x,y,z,w,h,d,mat=dark){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);g.add(m);return m}
function cylinder(g,x,y,z,r,h,mat=silver,inner=0){let geom;if(inner){const shape=new T.Shape();shape.absarc(0,0,r,0,Math.PI*2,false);const hole=new T.Path();hole.absarc(0,0,inner,0,Math.PI*2,true);shape.holes.push(hole);geom=new T.ExtrudeGeometry(shape,{depth:h,bevelEnabled:false,curveSegments:32});geom.rotateX(-Math.PI/2);geom.translate(0,-h/2,0);}else geom=new T.CylinderGeometry(r,r,h,32);const m=new T.Mesh(geom,mat);m.position.set(x,y,z);g.add(m);return m}
function link(g,a,b,r,mat=blue){const start=new T.Vector3(...a),end=new T.Vector3(...b),delta=end.clone().sub(start);const m=new T.Mesh(new T.CylinderGeometry(r,r,delta.length(),12),mat);m.position.copy(start.add(end).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());g.add(m);return m}
function label(g,text,x,y,z){const c=document.createElement('canvas');c.width=512;c.height=80;const ctx=c.getContext('2d');ctx.fillStyle='#121d2ce8';ctx.fillRect(0,0,512,80);ctx.font='500 30px Arial';ctx.textAlign='center';ctx.fillStyle='#d5e7ff';ctx.fillText(text,256,51);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const spr=new T.Sprite(new T.SpriteMaterial({map:tex,depthTest:false}));spr.position.set(x,y,z);spr.scale.set(2.5,.39,1);g.add(spr);return spr}
function workcell(scene){
 const root=new T.Group();scene.add(root);box(root,0,-.14,0,11,.25,8.5);const groups={};for(const k of ['bearings','shafts','lids','assembly','exit']){groups[k]=new T.Group();root.add(groups[k]);}
 const robot=new T.Group();root.add(robot);cylinder(robot,0,.2,0,.65,.4);cylinder(robot,0,.75,0,.42,.7,blue);link(robot,[0,.8,0],[.3,2.5,.1],.28);link(robot,[.3,2.5,.1],[.2,2.1,1.6],.23);cylinder(robot,.3,2.5,.1,.33,.5,dark);link(robot,[.2,2.1,1.6],[.2,1.6,1.8],.16,silver);box(robot,.2,1.4,1.8,.5,.25,.35,silver);box(robot,0,1.15,1.8,.1,.5,.15);box(robot,.4,1.15,1.8,.1,.5,.15);
 const b=groups.bearings;cylinder(b,-3,.75,-.2,1.1,1.4,dark);cylinder(b,-3,1.55,-.2,1.12,.2,silver,.83);for(let i=0;i<9;i++){const a=i/9*Math.PI*2;cylinder(b,-3+.75*Math.cos(a),1.59,-.2+.75*Math.sin(a),.14,.12,silver,.07);}box(b,-1.9,1.4,.2,1.2,.12,.45,silver);label(b,'BEARING FEEDER',-3,2.4,-.2);
 const sh=groups.shafts;box(sh,3,.7,0,2,.2,1.7);for(const x of [2.5,3,3.5])for(const z of [-.5,0,.5]){cylinder(sh,x,1,z,.1,.5);cylinder(sh,x,.91,z,.16,.13)}label(sh,'SHAFT TRAY',3,1.95,0);
 const lids=groups.lids;box(lids,0,1,-2.5,1.4,1.8,.2);const chute=box(lids,0,1.75,-2,1.3,.12,2.5,silver);chute.rotation.x=.38;for(let i=0;i<4;i++){const lid=cylinder(lids,0,1.47+i*.19,-1.2-i*.46,.4,.08,blue,.12);lid.rotation.x=.38;}label(lids,'LID CHUTE',0,3,-2.5);
 const assembly=groups.assembly;box(assembly,0,.6,2.25,1.5,1.1,1.15);box(assembly,0,1.2,2.25,.65,.32,.65,silver);cylinder(assembly,0,1.41,2.25,.16,.09,dark,.075);cylinder(assembly,0,1.6,2.25,.075,.35);box(assembly,.8,1.1,2.1,.16,.2,.3,blue);label(assembly,'ASSEMBLY',-.7,2,3.35);
 const ex=groups.exit;box(ex,3,1,2.75,3.5,.3,1.2);for(let i=0;i<11;i++){const roller=cylinder(ex,1.5+i*.28,1.16,2.75,.09,1.05,silver);roller.rotation.x=Math.PI/2;}box(ex,3.7,1.4,2.75,.6,.3,.6,blue);label(ex,'EXIT',3.5,2,3.5);
 const notes={all:'A report-based reconstruction of the part flow. Select a station to explore.',bearings:'Bearing feeder: a vibratory bowl aligns bearings. A proximity sensor checks pickup readiness.',shafts:'Shaft tray: pre-aligned slots hold shafts for pickup. The report proposes fill-level monitoring.',lids:'Lid chute: gravity brings oriented lids to the pickup point; a photoelectric sensor checks arrival.',assembly:'Assembly: insert bearing, then shaft, then lid. Proposed vision and force checks support alignment.',exit:'Exit conveyor: transfer the completed assembly and check part presence at the outgoing station.'};
 return {target:[0,.8,0],position:[10,10,14],change(value){for(const [k,g] of Object.entries(groups))g.traverse(o=>{if(o.isMesh){if(!o.userData.material)o.userData.material=o.material;o.material=value==='all'||k===value?o.userData.material:rubber;}});return notes[value]}};
}
function turtlebot(scene){
 const robot=new T.Group();scene.add(robot);for(const y of [.18,.5,.8]){const shelf=cylinder(robot,0,y,0,.38,.06,dark);for(const x of [-.23,.23])for(const z of [-.22,.22])cylinder(robot,x,y+.14,z,.018,.28,silver)}
 for(const x of [-.4,.4]){const wheel=cylinder(robot,x,.18,0,.19,.1,rubber);wheel.rotation.z=Math.PI/2;const hub=cylinder(robot,x,.18,0,.09,.11,silver);hub.rotation.z=Math.PI/2;}box(robot,0,.4,0,.28,.27,.35,blue);cylinder(robot,0,.91,0,.14,.14,rubber);cylinder(robot,0,.98,0,.115,.035,blue);
 const ground=new T.GridHelper(4,16,0x506c8e,0x293e55);ground.position.y=-.03;scene.add(ground);
 const obstacle=box(scene,0,.2,-1.4,.38,.4,.3,silver);
 const positions=[0,.04,0];for(let i=0;i<=30;i++){const angle=(-15+i)*Math.PI/180;positions.push(Math.sin(angle)*1,.04,-Math.cos(angle)*1)}const idx=[];for(let i=1;i<31;i++)idx.push(0,i,i+1);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setIndex(idx);geo.computeVertexNormals();const sector=new T.Mesh(geo,new T.MeshBasicMaterial({color:0x71aaff,transparent:true,opacity:.27,side:T.DoubleSide}));scene.add(sector);
 const rays=[];for(const a of [-15,0,15]){const p=[new T.Vector3(0,.91,0),new T.Vector3(Math.sin(a*Math.PI/180),.2,-Math.cos(a*Math.PI/180))];const line=new T.Line(new T.BufferGeometry().setFromPoints(p),new T.LineBasicMaterial({color:0x75b0ff}));scene.add(line);rays.push(line)}
 // Visual units: two units per metre for obstacle distance; robot geometry is approximate.
 label(scene,'LiDAR FRONT SECTOR ±15°',0,1.35,-1.3).scale.set(1.75,.27,1);label(scene,'0.5 m THRESHOLD',1.2,.08,-1.1).scale.set(1.15,.18,1);
 return {target:[0,.35,-.6],position:[3,2.6,3],change(value){const distance=Number(value)/100;obstacle.position.z=-distance*2-.15;const blocked=distance<.5;obstacle.material=blocked?blue:silver;sector.material.color.setHex(blocked?0xffb56b:0x71aaff);return blocked?'Obstacle detected: stop, wait 3 seconds, then turn 90° clockwise if the obstacle remains. Check again before moving.':"Path clear: the report's controller commands 0.15 m/s forward motion."}};
}
function nanotube(scene){
 const layers=[];const r=1.0;const columns=14,rows=9;const circumference=2*Math.PI*r;const a=circumference/(columns*Math.sqrt(3));
 for(let layer=0;layer<3;layer++){const g=new T.Group();scene.add(g);layers.push(g);const radius=r+layer*.28;const edgeMap=new Set();const bonds=[];const pts=new Map();
 for(let row=0;row<rows;row++)for(let col=0;col<columns;col++){
  const cx=Math.sqrt(3)*a*(col+(row%2)*.5),cy=1.5*a*row;
  const corners=[];for(let j=0;j<6;j++){const ang=(60*j+30)*Math.PI/180;const u=cx+a*Math.cos(ang),v=cy+a*Math.sin(ang);const theta=u/circumference*Math.PI*2;const p=new T.Vector3(radius*Math.cos(theta),v-1.5*a*(rows-1)/2,radius*Math.sin(theta));const key=p.toArray().map(n=>n.toFixed(4)).join(',');pts.set(key,p);corners.push(key)}
  for(let j=0;j<6;j++){const pair=[corners[j],corners[(j+1)%6]].sort();const key=pair.join('|');if(!edgeMap.has(key)){edgeMap.add(key);bonds.push(...pts.get(pair[0]).toArray(),...pts.get(pair[1]).toArray())}}
 }
 const material=new T.LineBasicMaterial({color:layer===0?0xb5d5ff:layer===1?0x528bd2:0x365a85,transparent:layer>0,opacity:layer>0?.7:1});const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(bonds,3));g.add(new T.LineSegments(geometry,material));
 const spheres=new T.InstancedMesh(new T.SphereGeometry(.035,7,5),layer===0?silver:blue,pts.size);const matrix=new T.Matrix4();let k=0;for(const p of pts.values()){matrix.makeTranslation(p.x,p.y,p.z);spheres.setMatrixAt(k++,matrix)}g.add(spheres);g.rotation.z=Math.PI/2;g.visible=layer===0;
 }
 return {target:[0,0,0],position:[4,3,5],change(value){layers.forEach((g,i)=>g.visible=i===0||value==='multi');return value==='multi'?'Multiple concentric carbon lattice walls. Layer spacing is enlarged for clarity and is not to atomic scale.':'A single carbon lattice wrapped into a tube. The model explains structure, not material performance.'}};
}
const builders={workcell,turtlebot,nanotube};
function init(panel){const stage=panel.querySelector('.mini-stage'),desc=panel.querySelector('.mini-description');try{
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
 const scene=new T.Scene();const camera=new T.PerspectiveCamera(38,1,.05,200);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=false;controls.minDistance=2;controls.maxDistance=35;
 const env=new RoomEnvironment(),gen=new T.PMREMGenerator(renderer);scene.environment=gen.fromScene(env,.02).texture;env.dispose();gen.dispose();scene.add(new T.HemisphereLight(0xddeaff,0x2a3b50,3));const light=new T.DirectionalLight(0xcadfff,3);light.position.set(3,8,5);scene.add(light);
 const model=builders[panel.dataset.model](scene);function draw(){renderer.render(scene,camera)}function reset(){camera.position.set(...model.position);controls.target.set(...model.target);controls.update();draw()}function zoom(n){const v=camera.position.clone().sub(controls.target).multiplyScalar(n).clampLength(2,35);camera.position.copy(controls.target).add(v);controls.update();draw()}
 stage.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');stage.querySelector('img').hidden=true;stage.dataset.loaded='true';panel.querySelector('.mini-reset').addEventListener('click',reset);controls.addEventListener('change',draw);
 new ResizeObserver(()=>{const {width,height}=stage.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.zoom=Math.min(1,Math.max(.4,camera.aspect/1.5));camera.updateProjectionMatrix();draw()}).observe(stage);
 const option=panel.querySelector('.model-option');if(option){const applyOption=()=>{desc.textContent=model.change(option.value);draw()};option.addEventListener('change',applyOption);applyOption()}
 const range=panel.querySelector('input');if(range){const applyDistance=()=>{panel.querySelector('output').textContent=(Number(range.value)/100).toFixed(2)+' m';desc.textContent=model.change(range.value);draw()};range.addEventListener('input',applyDistance);applyDistance()}
 stage.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')reset();else if(e.key==='+'||e.key==='=')zoom(.85);else if(e.key==='-')zoom(1.15);else if(e.key.startsWith('Arrow')){const v=camera.position.clone().sub(controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight')v.applyAxisAngle(new T.Vector3(0,1,0),e.key==='ArrowLeft'?.12:-.12);else v.y+=e.key==='ArrowUp'?.3:-.3;camera.position.copy(controls.target).add(v);controls.update();draw()}else return;e.preventDefault()});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();stage.querySelector('img').hidden=false;renderer.domElement.hidden=true;desc.textContent='Still diagram shown. Reload to restore 3D.';panel.querySelectorAll('button,input,select').forEach(c=>c.disabled=true)});reset();
 window.__projectViewers??={};window.__projectViewers[panel.dataset.model]={scene,camera,renderer,controls,draw};
 }catch(e){stage.dataset.loaded='fallback';desc.textContent='Still diagram shown. Interactive 3D is unavailable in this browser.';panel.querySelectorAll('button,input,select').forEach(c=>c.disabled=true);console.warn('Project diagram fallback:',e.message)}}
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){observer.unobserve(entry.target);init(entry.target)}},{rootMargin:'200px'});document.querySelectorAll('.mini-viewer').forEach(panel=>observer.observe(panel));
